language: ruby
services:
  - mongodb
  - redis-server
rvm:
  - 2.1.1
script:
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake rspec-rerun:spec
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
